# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: gomod
    directory: / # location of go.mod
    schedule:
      interval: daily
