sonar.projectName=ryclarke:batch-tool
sonar.sourceEncoding=UTF-8
sonar.language=go
sonar.go.coverage.reportPaths=coverage.out

sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
